allow-missing-formatter = false
excludes = ["*.md", "*.yaml", "*.toml", "*.lock", ".devenv/*", ".git/*"]
formatters = ["nix"]
on-unmatched = "info"
tree-root-cmd = "git rev-parse --show-toplevel"
verbose = 1
walk = "filesystem"

[formatter.nix]
command = "nixfmt"
options = [ "--width=80", "--indent=2" ]
includes = ["*.nix"]
excludes = []
priority = 0
